// <auto-generated />
using System;
using JBScraper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JBScraper.Migrations
{
    [DbContext(typeof(JBScraperContext))]
    [Migration("20180617052629_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JBScraper.Models.PortfolioInfo", b =>
                {
                    b.Property<int>("PortfolioInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CaptureDate");

                    b.Property<double>("DayGain");

                    b.Property<double>("PercentDayGain");

                    b.Property<double>("PercentTotalGain");

                    b.Property<double>("PortfolioValue");

                    b.Property<double>("TotalGain");

                    b.HasKey("PortfolioInfoId");

                    b.ToTable("PortfolioInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
