// <auto-generated />
using System;
using JBScraper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JBScraper.Migrations
{
    [DbContext(typeof(JBScraperContext))]
    partial class JBScraperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JBScraper.Models.PortfolioInfo", b =>
                {
                    b.Property<int>("PortfolioInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CaptureDate");

                    b.Property<double>("DayGain");

                    b.Property<double>("PercentDayGain");

                    b.Property<double>("PercentTotalGain");

                    b.Property<double>("PortfolioValue");

                    b.Property<double>("TotalGain");

                    b.HasKey("PortfolioInfoId");

                    b.ToTable("PortfolioInfo");
                });

            modelBuilder.Entity("JBScraper.Models.StockInfo", b =>
                {
                    b.Property<int>("StockInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PortfolioInfoId");

                    b.Property<double>("StockCostBasis");

                    b.Property<double>("StockCurrentPrice");

                    b.Property<double>("StockDayGain");

                    b.Property<double>("StockDayGainPercent");

                    b.Property<int>("StockLots");

                    b.Property<double>("StockMarketValue");

                    b.Property<string>("StockNotes");

                    b.Property<double>("StockPriceChange");

                    b.Property<double>("StockPriceChangePercent");

                    b.Property<double>("StockShares");

                    b.Property<string>("StockSymbol");

                    b.Property<double>("StockTotalGain");

                    b.Property<double>("StockTotalGainPercent");

                    b.HasKey("StockInfoId");

                    b.HasIndex("PortfolioInfoId");

                    b.ToTable("StockInfo");
                });

            modelBuilder.Entity("JBScraper.Models.StockInfo", b =>
                {
                    b.HasOne("JBScraper.Models.PortfolioInfo", "PortfolioInfo")
                        .WithMany("StockInfo")
                        .HasForeignKey("PortfolioInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
